name: Build App

on: [push]

jobs:
  build:
  
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
     
      - name: Build
        run: |
          & "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/MSBuild/Current/Bin/MSBuild.exe" ermcotest/ermcotest.sln /p:Configuration=release
